import { Router } from 'express';
import * as dataController from '../controllers/dataController.js';
import * as presetController from '../controllers/presetController.js';
import * as authController from '../controllers/authController.js';
import * as siteConfigController from '../controllers/siteConfigController.js';
import * as playerController from '../controllers/playerController.js';
import { authLimiter, writeLimiter } from '../middleware/security.js';
const router = Router();
router.post('/auth/register', authLimiter, authController.register);
router.post('/auth/login', authLimiter, authController.login);
router.get('/site-config', siteConfigController.getSiteConfig);
router.use(authController.authRequired);
router.get('/auth/me', authController.me);
router.get('/player', playerController.getPlayer);
router.get('/player/refresh-status', playerController.getRefreshStatus);
router.post('/player/refresh', writeLimiter, playerController.postRefresh);
router.get('/data/:collection', dataController.getCollection);
router.get('/presets', presetController.listPresets);
router.get('/presets/:name', presetController.getPreset);
router.post('/presets', writeLimiter, presetController.createPreset);
router.put('/presets/:name', writeLimiter, presetController.updatePreset);
router.post('/presets/:name/rename', writeLimiter, presetController.renamePreset);
router.delete('/presets/:name', writeLimiter, presetController.deletePreset);
export default router;
